name: sxwnl_spa_dart
description: Astronomical calendar library with lunar, solar terms, gan-zhi and true solar time.
version: 0.9.0
repository: https://github.com/RedSC1/sxwnl_spa_dart

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  tuple: ^2.0.2
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
